import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const prompts = {
  SIAP: "Siap",
  SILAKAN_BICARA: "Silakan bicara",
  TEGANGAN: "Tegangan",
  DAYA: "Daya",
  ARUS: "Arus",
  VOLT: "Volt",
  WATT: "Watt",
  AMPERE: "Ampere",
  DERAJAT: "derajat",
  SUHU_DIATUR: "Suhu berhasil diatur",
  AC_DIMATIKAN: "AC berhasil dimatikan",
  AC_DINYALAKAN: "AC berhasil dinyalakan",
  TEKAN_ON_REMOTE: "Tekan ON pada remote",
  TEKAN_OFF_REMOTE: "Tekan OFF pada remote",
  REMOTE_TERSIMPAN: "Remote berhasil disimpan",
  PERINTAH_TIDAK_DIKENALI: "Perintah belum dikenali",
  INTERNET_TIDAK_TERSEDIA: "Internet tidak tersedia",
  METER_TIDAK_TERSEDIA: "Data meter tidak tersedia",
  WAKTU_DISKON_DIMULAI: "Waktu diskon dimulai",
  WAKTU_DISKON_SELESAI: "Waktu diskon selesai",
  PERINGATAN: "Peringatan",
  TEGANGAN_RENDAH: "Tegangan rendah",
  TEGANGAN_TINGGI: "Tegangan tinggi",
  DAYA_TINGGI: "Daya tinggi",
  NOL: "nol", SATU: "satu", DUA: "dua", TIGA: "tiga", EMPAT: "empat",
  LIMA: "lima", ENAM: "enam", TUJUH: "tujuh", DELAPAN: "delapan", SEMBILAN: "sembilan",
  SEPULUH: "sepuluh", SEBELAS: "sebelas", DUA_BELAS: "dua belas", TIGA_BELAS: "tiga belas",
  EMPAT_BELAS: "empat belas", LIMA_BELAS: "lima belas", ENAM_BELAS: "enam belas",
  TUJUH_BELAS: "tujuh belas", DELAPAN_BELAS: "delapan belas", SEMBILAN_BELAS: "sembilan belas",
  PULUH: "puluh", RATUS: "ratus", SERATUS: "seratus", RIBU: "ribu", SERIBU: "seribu",
  KOMA: "koma", MINUS: "minus"
};

const dir = mkdtempSync(join(tmpdir(), "device-a-voice-"));
let header = `#pragma once\n#include <Arduino.h>\n\n// Generated by tools/generate_voice_prompts.mjs\n// 11.025 kHz mono unsigned 8-bit PCM, stored in flash.\n`;
let total = 0;

for (const [name, text] of Object.entries(prompts)) {
  const caf = join(dir, `${name}.caf`);
  const raw = join(dir, `${name}.raw`);
  execFileSync("say", ["-v", "Damayanti", "-r", "185", "--data-format=LEI16@22050", "-o", caf, text]);
  execFileSync("ffmpeg", ["-loglevel", "error", "-y", "-i", caf, "-ac", "1", "-ar", "11025",
    "-af", "loudnorm=I=-18:TP=-2:LRA=7", "-f", "u8", raw]);
  const data = readFileSync(raw);
  if (data.length < 100) throw new Error(`TTS menghasilkan audio kosong untuk prompt ${name}`);
  total += data.length;
  const bytes = [];
  for (let i = 0; i < data.length; i += 16) {
    bytes.push("  " + [...data.subarray(i, i + 16)].map(v => `0x${v.toString(16).padStart(2, "0")}`).join(", "));
  }
  header += `\nstatic const uint8_t VOICE_${name}[] PROGMEM = {\n${bytes.join(",\n")}\n};\n`;
  header += `static const size_t VOICE_${name}_LEN = sizeof(VOICE_${name});\n`;
}

header += `\nstatic const size_t VOICE_PROMPTS_TOTAL_BYTES = ${total};\n`;
writeFileSync("src/voice_prompts.h", header);
rmSync(dir, { recursive: true, force: true });
console.log(`Generated ${Object.keys(prompts).length} prompts, ${total} PCM bytes.`);
