#pragma once
#include <Arduino.h>

// UI disimpan di flash. Tidak dialokasikan sebagai String besar di heap.
static const char WEB_UI_HTML[] PROGMEM = R"HTML(
<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#07111f">
  <title>Device A</title>
  <style>
    :root{--bg:#07111f;--panel:#0d1b2d;--panel2:#12243a;--line:#203751;--text:#f4f7fb;--muted:#91a5ba;--blue:#57a8ff;--green:#42dc8e;--red:#ff6975;--amber:#ffbd66}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}button,input{font:inherit}main{width:min(1050px,100%);margin:auto;padding:20px 18px 92px}
    header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}h1{margin:0;font-size:clamp(27px,5vw,40px);letter-spacing:-.04em}.sub,.hint{color:var(--muted);font-size:13px}.sub{margin-top:5px}.badge,.pill{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--line);border-radius:999px;padding:8px 11px;background:#142238;font-size:12px;font-weight:800}.dot{width:8px;height:8px;border-radius:50%;background:var(--red)}.online .dot,.ok .dot{background:var(--green)}
    nav{position:sticky;top:8px;z-index:10;display:grid;grid-template-columns:repeat(5,1fr);gap:6px;padding:6px;margin-bottom:16px;border:1px solid var(--line);border-radius:16px;background:rgba(7,17,31,.94);backdrop-filter:blur(12px)}nav button{border:0;border-radius:11px;min-height:44px;background:transparent;color:var(--muted);font-weight:800;cursor:pointer}nav button.active{background:var(--blue);color:#06101c}
    .tab{display:none}.tab.active{display:block}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:12px}.card{grid-column:span 6;padding:17px;border:1px solid var(--line);border-radius:17px;background:linear-gradient(180deg,var(--panel2),var(--panel))}.full{grid-column:1/-1}.third{grid-column:span 4}.metric{grid-column:span 3}.card h2{font-size:17px;margin:0 0 14px}.label{color:var(--muted);font-size:11px;font-weight:850;text-transform:uppercase;letter-spacing:.08em}.value{font-size:clamp(26px,5vw,38px);font-weight:850;margin-top:7px;letter-spacing:-.04em}.unit{font-size:.46em;color:var(--muted);margin-left:4px}.row{display:grid;grid-template-columns:minmax(100px,1fr) minmax(0,auto);gap:12px;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.06);font-size:14px}.row:last-child{border:0}.row span{color:var(--muted)}.row strong{text-align:right;overflow-wrap:anywhere}
    .actions{display:flex;gap:9px;flex-wrap:wrap}.actions button,.primary{border:0;border-radius:11px;min-height:44px;padding:0 14px;background:var(--blue);color:#06101c;font-weight:850;cursor:pointer}.actions .secondary{background:#1b314c;color:var(--text);border:1px solid #2c4b6b}.actions .danger{background:#482135;color:var(--text);border:1px solid #75364e}button:disabled{opacity:.55;cursor:wait}.meter{height:15px;border-radius:999px;overflow:hidden;background:#06101c;border:1px solid var(--line);margin:14px 0}.meter div{height:100%;width:0;background:linear-gradient(90deg,var(--green),var(--amber),var(--red));transition:width .15s}.focus{border-color:#35648e;background:linear-gradient(145deg,#143150,#0d1b2d)}
    .form{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end}.form.compact{grid-template-columns:1fr auto}.field label{display:block;margin-bottom:7px;color:var(--muted);font-size:11px;text-transform:uppercase;font-weight:850;letter-spacing:.08em}.field input{width:100%;height:44px;padding:0 11px;background:#07111f;color:var(--text);border:1px solid var(--line);border-radius:11px;outline:none}.field input:focus{border-color:var(--blue)}code{display:block;padding:11px;border:1px solid var(--line);border-radius:10px;background:#07111f;color:#afd7ff;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}details summary{cursor:pointer;font-weight:800}.notice{padding:12px;border-radius:12px;border:1px solid #684b29;background:#2b2118;color:#ffd293;font-size:13px}
    @media(max-width:720px){main{padding:14px 12px 96px}header{flex-direction:column}.card,.third,.metric{grid-column:1/-1}.metric{display:flex;align-items:center;justify-content:space-between}.metric .value{margin:0}.form,.form.compact{grid-template-columns:1fr}nav{position:fixed;top:auto;bottom:8px;left:8px;right:8px;margin:0}nav button{font-size:11px;padding:0 4px}.row{font-size:13px}}
  </style>
</head>
<body><main>
  <header><div><h1>Device A</h1><div class="sub">ESP32-S3 Smart AC Controller • <span id="prefixText">-</span></div></div><div id="statusBadge" class="badge"><span class="dot"></span><span id="statusText">Menghubungkan...</span></div></header>
  <nav id="tabs"><button class="active" data-tab="home">Ringkasan</button><button data-tab="audio">Audio</button><button data-tab="ir">Infrared</button><button data-tab="meter">Meter</button><button data-tab="system">Sistem</button></nav>

  <section id="home" class="tab active"><div class="grid">
    <article class="card metric"><div><div class="label">Tegangan</div><div class="value" id="homeVoltage">--</div></div></article>
    <article class="card metric"><div><div class="label">Arus</div><div class="value" id="homeCurrent">--</div></div></article>
    <article class="card metric"><div><div class="label">Daya</div><div class="value" id="homePower">--</div></div></article>
    <article class="card metric"><div><div class="label">Energi</div><div class="value" id="homeEnergy">--</div></div></article>
    <article class="card full focus"><h2>Fokus pengujian: Audio</h2><p class="hint">Infrared dan Modbus sudah berfungsi. Jalankan tes microphone lalu dengarkan suara speaker.</p><div class="actions"><button id="audioTestButton" onclick="runAudioTests()">Uji Mic + Speaker</button><button class="secondary" onclick="showTab('audio')">Buka Tab Audio</button></div><div class="row"><span>Microphone</span><strong id="homeMic">--</strong></div><div class="row"><span>Speaker</span><strong id="homeSpeaker">--</strong></div></article>
    <article class="card third"><h2>Infrared</h2><div class="pill ok"><span class="dot"></span>Sudah OK</div><div class="hint" style="margin-top:12px">RX GPIO4 • TX GPIO10</div></article>
    <article class="card third"><h2>Modbus</h2><div id="homeModbusPill" class="pill"><span class="dot"></span><span id="homeModbus">Memuat...</span></div><div class="hint" style="margin-top:12px">2400 bps • 8E1 • Slave 1</div></article>
    <article class="card third"><h2>OLED</h2><div class="pill"><span class="dot"></span>Nonaktif</div><div class="hint" style="margin-top:12px">Hardware rusak; tidak masuk alur pengujian.</div></article>
  </div></section>

  <section id="audio" class="tab"><div class="grid">
    <article class="card full focus"><h2>Uji Audio Otomatis</h2><p class="hint">Setelah menekan tombol, segera bicara dekat microphone selama empat detik. Sesudah itu speaker akan mengucapkan kalimat uji.</p><div class="actions"><button id="audioTestButton2" onclick="runAudioTests()">Mulai Uji Audio</button></div><div class="row"><span>Proses</span><strong id="audioSequence">Belum dijalankan</strong></div></article>
    <article class="card"><h2>Microphone I2S</h2><div class="actions"><button onclick="micTest()">Uji Bicara 4 Detik</button></div><div class="meter"><div id="micBar"></div></div><div class="row"><span>Status</span><strong id="microphoneStatus">--</strong></div><div class="row"><span>Level</span><strong id="micLevel">--</strong></div><div class="row"><span>Hasil</span><strong id="micResult">--</strong></div><p class="hint">BCLK GPIO6 • WS GPIO7 • DATA GPIO15 • L/R ke GND</p></article>
    <article class="card"><h2>Speaker MAX98357A</h2><div class="actions"><button onclick="ampTest('voice')">Bicara</button><button class="secondary" onclick="ampTest('tone')">Tone 1 kHz</button><button class="secondary" onclick="ampTest('beep')">Beep 3x</button><button class="secondary" onclick="ampTest('sweep')">Sweep</button></div><div class="row"><span>Status</span><strong id="amplifierStatus">--</strong></div><div class="row"><span>Tes terakhir</span><strong id="amplifierTest">--</strong></div><p class="hint">BCLK GPIO8 • WS GPIO9 • DIN GPIO11. Ucapan tersimpan offline di flash.</p></article>
  </div></section>

  <section id="ir" class="tab"><div class="grid"><article class="card full"><h2>Infrared Remote</h2><div class="notice">IR transmitter dan receiver sudah dinyatakan OK. Kontrol tetap tersedia jika diperlukan.</div><div class="actions" style="margin-top:14px"><button onclick="irLearn('on')">Learn ON</button><button onclick="irLearn('off')">Learn OFF</button><button class="secondary" onclick="irSend('on')">Send ON</button><button class="secondary" onclick="irSend('off')">Send OFF</button><button class="secondary" onclick="irTxTest()">Test TX/RX</button><button class="secondary" onclick="irBlink()">Blink 3s</button><button class="danger" onclick="irClear()">Hapus Rekaman</button></div><div class="row"><span>Mode</span><strong id="irLearn">--</strong></div><div class="row"><span>Rekaman ON/OFF</span><strong id="irLens">--</strong></div><div class="row"><span>Status</span><strong id="irStatus">--</strong></div><div class="row"><span>Test TX/RX</span><strong id="irTxTest">--</strong></div><p class="hint">Receiver OUT GPIO4 • Transmitter SIG GPIO10</p></article></div></section>

  <section id="meter" class="tab"><div class="grid">
    <article class="card metric"><div><div class="label">Voltage</div><div class="value" id="voltage">--</div></div></article><article class="card metric"><div><div class="label">Current</div><div class="value" id="current">--</div></div></article><article class="card metric"><div><div class="label">Active Power</div><div class="value" id="power">--</div></div></article><article class="card metric"><div><div class="label">Power Factor</div><div class="value" id="pf">--</div></div></article>
    <article class="card metric"><div><div class="label">Frequency</div><div class="value" id="frequency">--</div></div></article><article class="card metric"><div><div class="label">Total Energy</div><div class="value" id="energy">--</div></div></article><article class="card metric"><div><div class="label">Reactive</div><div class="value" id="reactive">--</div></div></article><article class="card metric"><div><div class="label">Apparent</div><div class="value" id="apparent">--</div></div></article>
    <article class="card"><h2>Energy Counter</h2><div class="row"><span>Total active</span><strong id="totalEnergy">--</strong></div><div class="row"><span>Forward</span><strong id="forwardEnergy">--</strong></div><div class="row"><span>Reverse</span><strong id="reverseEnergy">--</strong></div></article>
    <article class="card"><h2>Status Modbus</h2><div class="actions"><button onclick="readMeterNow()">Baca Sekarang</button></div><div class="row"><span>Status</span><strong id="detailStatus">--</strong></div><div class="row"><span>Response</span><strong id="responseStatus">--</strong></div><div class="row"><span>OK / Error</span><strong id="counter">--</strong></div></article>
    <article class="card full"><details><summary>Raw diagnostik Modbus</summary><div class="row"><span>Error detail</span><strong id="errorDetail">--</strong></div><p class="label">TX</p><code id="tx">-</code><p class="label">RX</p><code id="rx">-</code><p class="label">Registers</p><code id="registers">-</code></details></article>
  </div></section>

  <section id="system" class="tab"><div class="grid">
    <article class="card full"><h2>WiFi Internet</h2><form class="form" onsubmit="saveWifi(event)"><div class="field"><label for="wifiSsidInput">SSID router</label><input id="wifiSsidInput" maxlength="32" autocomplete="off"></div><div class="field"><label for="wifiPassInput">Password</label><input id="wifiPassInput" type="password" maxlength="64" placeholder="Kosongkan jika tidak berubah"></div><button class="primary" type="submit">Sambungkan</button></form><div class="actions" style="margin-top:10px"><button class="secondary" onclick="wifiReconnect()">Reconnect</button><button class="danger" onclick="wifiClear()">Hapus WiFi</button></div></article>
    <article class="card"><h2>Koneksi</h2><div class="row"><span>WiFi</span><strong id="wifiStatus">--</strong></div><div class="row"><span>SSID</span><strong id="staTarget">--</strong></div><div class="row"><span>Password</span><strong id="staPassStatus">--</strong></div><div class="row"><span>IP</span><strong id="staIp">--</strong></div><div class="row"><span>MQTT</span><strong id="mqttStatus">--</strong></div><div class="row"><span>Topic</span><strong id="mqttTopic">--</strong></div></article>
    <article class="card"><h2>Perangkat</h2><div class="row"><span>Modbus polling</span><strong id="modbusPolling">--</strong></div><div class="row"><span>IR transmitter</span><strong id="irTxReady">--</strong></div><div class="row"><span>OLED</span><strong>Nonaktif — hardware rusak</strong></div><div class="row"><span>Memori</span><strong id="memoryStatus">--</strong></div><div class="actions"><button class="secondary" onclick="led('red')">LED Merah</button><button class="secondary" onclick="led('green')">Hijau</button><button class="secondary" onclick="led('blue')">Biru</button><button class="secondary" onclick="led('off')">Mati</button></div></article>
    <article class="card full"><h2>Prefix Device/MQTT</h2><form class="form compact" onsubmit="savePrefix(event)"><div class="field"><label for="prefixInput">Prefix</label><input id="prefixInput" maxlength="48" placeholder="hems/ac"></div><button class="primary" type="submit">Simpan</button></form></article>
  </div></section>
</main>
<script>
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
function n(v,d){const x=Number(v);return Number.isFinite(x)?x.toFixed(d):'--'}
function metric(id,v,d,u){$(id).innerHTML=n(v,d)+`<span class="unit">${u}</span>`}
function showTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));location.hash=name}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
async function refresh(){try{const r=await fetch('/status',{cache:'no-store'}),d=await r.json();$('statusBadge').className=d.meterOnline?'badge online':'badge';$('statusText').textContent=d.meterOnline?'Device Online':d.meterStatus;$('prefixText').textContent=d.devicePrefix||'-';
  metric('homeVoltage',d.voltage,1,' V');metric('homeCurrent',d.current,3,' A');metric('homePower',d.activePower,3,' kW');metric('homeEnergy',d.totalEnergy,2,' kWh');$('homeMic').textContent=d.microphoneTestResult;$('homeSpeaker').textContent=`${d.amplifierLastTest} • ${d.amplifierMessage}`;$('homeModbus').textContent=d.meterOnline?'Sudah OK / Online':d.meterStatus;$('homeModbusPill').className=d.meterOnline?'pill ok':'pill';
  $('microphoneStatus').textContent=d.microphoneReady?d.microphoneStatus:'Tidak siap';$('micLevel').textContent=`RMS ${d.microphoneRms} • peak ${d.microphonePeak}`;$('micResult').textContent=d.microphoneTestResult;$('micBar').style.width=`${Math.min(100,Math.sqrt(Math.max(0,d.microphoneRms))*3)}%`;$('amplifierStatus').textContent=d.amplifierReady?d.amplifierStatus:`${d.amplifierStatus}: ${d.amplifierMessage}`;$('amplifierTest').textContent=`${d.amplifierLastTest} • ${d.amplifierMessage} • error ${d.amplifierWriteErrors}/${d.amplifierShortWrites}`;
  $('irLearn').textContent=d.irLearn;$('irLens').textContent=`ON ${d.irOnLen} / OFF ${d.irOffLen}`;$('irStatus').textContent=`${d.irStatus}: ${d.irMessage}`;$('irTxTest').textContent=`${d.irTestResult} (${d.irTestTransitions} transisi)`;
  metric('voltage',d.voltage,1,' V');metric('current',d.current,3,' A');metric('power',d.activePower,4,' kW');metric('pf',d.powerFactor,3,'');metric('frequency',d.frequency,2,' Hz');metric('energy',d.totalEnergy,2,' kWh');metric('reactive',d.reactivePower,4,' kvar');metric('apparent',d.apparentPower,4,' kVA');$('totalEnergy').textContent=`${n(d.totalEnergy,2)} kWh`;$('forwardEnergy').textContent=`${n(d.forwardEnergy,2)} kWh`;$('reverseEnergy').textContent=`${n(d.reverseEnergy,2)} kWh`;$('detailStatus').textContent=d.meterStatus;$('responseStatus').textContent=`RX ${d.lastResponseBytes} byte • ${d.pollMs} ms`;$('counter').textContent=`${d.meterOk} OK / ${d.meterErr} ERR`;$('errorDetail').textContent=d.meterError;$('tx').textContent=d.lastRequestHex;$('rx').textContent=d.lastResponseHex;$('registers').textContent=d.lastRegistersHex;
  if(document.activeElement!==$('prefixInput'))$('prefixInput').value=d.devicePrefix||'';if(document.activeElement!==$('wifiSsidInput'))$('wifiSsidInput').value=d.staSsid||'';$('wifiStatus').textContent=d.wifiConnected?`Connected ${d.wifiRssi} dBm`:d.wifiStatus;$('staTarget').textContent=d.staSsid||'Belum diset';$('staPassStatus').textContent=d.staPasswordSet?`Tersimpan (${d.staPasswordLength} karakter)`:'Belum diset';$('staIp').textContent=d.wifiConnected?d.staIp:'-';$('mqttStatus').textContent=d.mqttConnected?`Connected • pub ${d.mqttOk}/${d.mqttErr}`:d.mqttStatus;$('mqttTopic').textContent=d.mqttStateTopic||'-';$('modbusPolling').textContent=d.modbusPolling?'Aktif':'Menunggu internet';$('irTxReady').textContent=d.irTxReady?'GPIO10 siap':'Tidak siap';$('memoryStatus').textContent=`Heap ${Math.round(d.freeHeap/1024)} KB • Flash ${Math.round(d.freeSketchSpace/1024)} KB bebas`;return d
}catch(e){$('statusBadge').className='badge';$('statusText').textContent='UI terputus';return null}}
async function micTest(){await fetch('/mic-test',{cache:'no-store'});await refresh()}
async function ampTest(a){$('amplifierTest').textContent='Menjalankan...';await fetch(`/amp-test?action=${a}`,{cache:'no-store'});await refresh()}
async function runAudioTests(){const bs=[$('audioTestButton'),$('audioTestButton2')];bs.forEach(b=>b.disabled=true);showTab('audio');try{$('audioSequence').textContent='BICARA SEKARANG — merekam level 4 detik';await micTest();await wait(4500);let d=await refresh();$('audioSequence').textContent=d?.microphoneTestResult||'Tes microphone gagal';await wait(600);$('audioSequence').textContent+=' • Memutar ucapan speaker...';await ampTest('voice');$('audioSequence').textContent=(d?.microphoneTestResult||'Mic selesai')+' • Speaker selesai, konfirmasi dengan pendengaran'}finally{bs.forEach(b=>b.disabled=false)}}
async function readMeterNow(){await fetch('/meter-read',{cache:'no-store'});await refresh()}async function led(c){await fetch(`/led?color=${c}`,{cache:'no-store'})}async function irLearn(s){await fetch(`/ir-learn?slot=${s}`,{cache:'no-store'});await refresh()}async function irSend(s){await fetch(`/ir-send?slot=${s}`,{cache:'no-store'});await refresh()}async function irTxTest(){await fetch('/ir-tx-test',{cache:'no-store'});await refresh()}async function irBlink(){await fetch('/ir-blink',{cache:'no-store'});await refresh()}async function irClear(){await fetch('/ir-clear',{cache:'no-store'});await refresh()}
async function saveWifi(e){e.preventDefault();const b=new URLSearchParams();b.set('ssid',$('wifiSsidInput').value);b.set('password',$('wifiPassInput').value);await fetch('/wifi-save',{method:'POST',body:b,cache:'no-store'});$('wifiPassInput').value='';await refresh()}async function wifiReconnect(){await fetch('/wifi-reconnect',{cache:'no-store'});await refresh()}async function wifiClear(){await fetch('/wifi-clear',{cache:'no-store'});$('wifiPassInput').value='';await refresh()}async function savePrefix(e){e.preventDefault();await fetch(`/prefix-save?value=${encodeURIComponent($('prefixInput').value)}`,{cache:'no-store'});await refresh()}
const start=location.hash.slice(1);if(['home','audio','ir','meter','system'].includes(start))showTab(start);refresh();setInterval(refresh,1000);
</script></body></html>
)HTML";
